language:
  - c
compiler:
  - gcc
cache:
  directories:
    - "${HOME}/.maixpy_cache"
env:
  global:
    - rev=$(git rev-parse --short HEAD)
    - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - curr_branch=$TRAVIS_BRANCH
branches:
  only:
    - master

stages:
  - name: maixpy_build

jobs:
  include:
    - stage: maixpy_build
      env: NAME="maixpy build"
      install:
        - sudo apt-get update
        - sudo apt-get install -y sshpass p7zip-full
        - wget https://github.com/kendryte/kendryte-gnu-toolchain/releases/download/v8.2.0-20190409/kendryte-toolchain-ubuntu-amd64-8.2.0-20190409.tar.xz
        - sudo tar -Jxf kendryte-toolchain-ubuntu-amd64-8.2.0-20190409.tar.xz -C /opt
        - rm -f kendryte-toolchain-ubuntu-amd64-8.2.0-20190409.tar.xz
      script:
        - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"
        - cd tools/release
        - chmod +x release.sh && ./release.sh || travis_terminate 1;
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
        - time_now=$(date "+%Y_%m_%d_%H_%M_%S")
        - cd bin
        - firmware_dir=`ls`
        - sudo sh -c "echo StrictHostKeyChecking no >>/etc/ssh/ssh_config"
        - sshpass -p ${USER_PASSWD} scp -r $firmware_dir ${SERVER_USER}@${SERVER_ADDR}:${SERVER_FOLDER_PATH}/${curr_branch}/
